apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-schedule
  namespace: smart-schedule
spec:
  rules:
    - host: smart-schedule.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smart-schedule-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: smart-schedule-api
                port:
                  number: 3000
