export type RuntimeEnvironmentContract = {
  APP_EDITION: "commercial" | "community";
  NODE_ENV: "development" | "production" | "test";
  HOST: string;
  PORT: number;
  DATABASE_URL: string;
  REDIS_URL: string;
  OBJECT_STORAGE_ENDPOINT?: string;
  OBJECT_STORAGE_ACCESS_KEY?: string;
  OBJECT_STORAGE_SECRET_KEY?: string;
  OBJECT_STORAGE_BUCKET?: string;
  OBJECT_STORAGE_USE_SSL: boolean;
  JWT_SECRET: string;
  SESSION_SECRET: string;
  SESSION_COOKIE_NAME: string;
  SESSION_TTL_SECONDS: number;
  RATE_LIMIT_WINDOW_MS: number;
  RATE_LIMIT_MAX: number;
  AUTH_SOCIAL_PROVIDERS?: string;
  CALENDARIFIC_API_BASE_URL: string;
  CALENDARIFIC_PORTAL_BASE_URL: string;
};
